using Iced.Intel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Ieo.EarthFileApi.Files.Scripts
{
   public class EarthEilData
   {
      public byte[] Consts { get; set; }
      public string ConstsStr => Encoding.UTF8.GetString(Consts);
      public EarthStateEil[] States { get; set; }
      public EarthCommandEil[] Commands { get; set; }
      public EarthEventEil[] Events { get; set; }
   }

   public class EarthCommandEil
   {
      public string Name { get; set; }
      public int Unknown { get; set; }
      public int Unknown2 { get; set; }
      public int Unknown3 { get; set; }
      public int Unknown4 { get; set; }
      internal byte[] Code { get; set; }
      public string Deassembly { get; set; }
   }

   public class EarthStateEil
   {
      public string Name { get; set; }
      internal byte[] Code { get; set; }
      public string Deassembly { get; set; }
   }

   public class EarthEventEil
   {
      public string Name { get; set; }
      internal byte[] Code { get; set; }
      public string Deassembly { get; set; }
   }

   public static class EilParser
   {
      public static EarthEilData Parse(EarthEcoMpData ecoMpData)
      {
         var codeOffsets = ecoMpData.StatesOffsets.Concat(ecoMpData.EventOffsets).Concat(ecoMpData.Commands.Select(c => c.CodeOffset)).OrderBy(i => i).ToArray();

         var eilData = new EarthEilData();
         eilData.Consts = ecoMpData.Consts.ToArray();
         eilData.States = ecoMpData.StatesOffsets.Select(so =>
         {
            var stateEil = new EarthStateEil();
            stateEil.Name = $"State_{so:X8}";
            var nextElementOffset = codeOffsets.Where(o => o > so).OrderBy(i => i).FirstOrDefault();
            var code = ecoMpData.Code.Skip(so);
            if (nextElementOffset != default)
               code = code.Take(nextElementOffset - so);
            stateEil.Code = code.ToArray();
            stateEil.Deassembly = Deassemble(ecoMpData, stateEil.Code, so);
            return stateEil;
         }).ToArray();
         eilData.Commands = ecoMpData.Commands.Select(c =>
         {
            if (c.CodeOffset == 0)
               return new EarthCommandEil
               {
                  Name = "NULL",
                  Code = Array.Empty<byte>(),
                  Deassembly = string.Empty,
               };
            var commandEil = new EarthCommandEil();
            commandEil.Name = $"Command_{c.CodeOffset:X8}";
            var nextElementOffset = codeOffsets.Where(o => o > c.CodeOffset).OrderBy(i => i).FirstOrDefault();
            var code = ecoMpData.Code.Skip(c.CodeOffset);
            if (nextElementOffset != default)
               code = code.Take(nextElementOffset - c.CodeOffset);
            commandEil.Code = code.ToArray();
            commandEil.Deassembly = Deassemble(ecoMpData, commandEil.Code, c.CodeOffset);
            commandEil.Unknown = c.Unknown;
            commandEil.Unknown2 = c.Unknown2;
            commandEil.Unknown3 = c.Unknown3;
            commandEil.Unknown4 = c.Unknown4;
            return commandEil;
         }).ToArray();
         eilData.Events = ecoMpData.EventOffsets.Select(eo =>
         {
            if (eo == 0)
               return new EarthEventEil
               {
                  Name = "NULL",
                  Code = Array.Empty<byte>(),
                  Deassembly = string.Empty,
               };
            var eventEil = new EarthEventEil();
            eventEil.Name = $"Event_{eo:X8}";
            var nextElementOffset = codeOffsets.Where(o => o > eo).OrderBy(i => i).FirstOrDefault();
            var code = ecoMpData.Code.Skip(eo);
            if (nextElementOffset != default)
               code = code.Take(nextElementOffset - eo);
            eventEil.Code = code.ToArray();
            eventEil.Deassembly = Deassemble(ecoMpData, eventEil.Code, eo);
            return eventEil;
         }).ToArray();

         return eilData;
      }

      private static string Deassemble(EarthEcoMpData ecoMpData, byte[] data, int offset)
      {
         var sb = new StringBuilder();

         var codeReader = new ByteArrayCodeReader(data);
         var decoder = Iced.Intel.Decoder.Create(32, codeReader);
         decoder.IP = (ulong)offset;
         ulong endRip = decoder.IP + (uint)data.Length;

         var instructions = new List<Instruction>();
         while (decoder.IP < endRip)
            instructions.Add(decoder.Decode());

         // Formatters: Masm*, Nasm*, Gas* (AT&T) and Intel* (XED).
         // There's also `FastFormatter` which is ~2x faster. Use it if formatting speed is more
         // important than being able to re-assemble formatted instructions.
         var formatter = new MasmFormatter();
         formatter.Options.FirstOperandCharIndex = 10;
         var output = new StringOutput();
         foreach (var instr in instructions)
         {
            // Don't use instr.ToString(), it allocates more, uses masm syntax and default options
            formatter.Format(instr, output);
            sb.Append(instr.IP.ToString("X8"));
            sb.Append(" ");
            int instrLen = instr.Length;
            int byteBaseIndex = (int)(instr.IP - (ulong)offset);
            var instrBytes = data.Skip(byteBaseIndex).Take(instrLen).ToArray();
            for (int i = 0; i < instrLen; i++)
               sb.Append(instrBytes[i].ToString("X2"));
            int missingBytes = 8 - instrLen;
            for (int i = 0; i < missingBytes; i++)
               sb.Append("  ");
            sb.Append(" ");
            if (instrBytes.SequenceEqual(new byte[] { 0xE8, 0x0, 0x0, 0x0, 0x0 }))
            {
               sb.AppendLine($"call      {FuncMapping[ecoMpData.FuncReferences.Single(fr => fr.CodeOffset == (int)instr.IP + 1).FunctionNumber]}");
               output.Reset();
            }
            else if (ecoMpData.ConstReferences.Any(c => c == (int)instr.IP + 1))
            {
               var str = output.ToStringAndReset();
               var constIndex = BitConverter.ToInt32(instrBytes, 1);
               var endIndex = ecoMpData.Consts.ToList().IndexOf(0x0, constIndex);
               string replaceStr;
               if (endIndex == default)
                  replaceStr = Encoding.UTF8.GetString(ecoMpData.Consts.Skip(constIndex).ToArray());
               else
                  replaceStr = Encoding.UTF8.GetString(ecoMpData.Consts, constIndex, endIndex - constIndex);
               sb.AppendLine($"{str.Substring(0, 14)}str:\"{replaceStr}\"");
            }
            else
            {
               sb.AppendLine(output.ToStringAndReset());
            }
               
         }

         return sb.ToString();
      }

      private static IReadOnlyDictionary<int, string> FuncMapping { get; set; } = new Dictionary<int, string>
      {
         {0, "Distance"},
         {1, "GetMaxSideColor"},
         {2, "GetEntranceZ"},
         {3, "GetEntranceY"},
         {4, "GetEntranceX"},
         {5, "Rand"},
         {6, "$SetAt"},
         {7, "$GetAt"},
         {8, "$SerializeInt"},
         {9, "$Assert"},
         {10, "TraceD"},
         {11, "Trace"},
         {12, "TraceD"},
         {13, "Trace"},
         {14, "ChangedCommandValue"},
         {15, "$Serialize"},
         {16, "$AddRef"},
         {17, "$Release"},
         {18, "IsWorkingSupplyCenterInPoint"},
         {19, "IsOnWorkingSupplyCenter"},
         {20, "InPlatoon"},
         {21, "MessageTalk"},
         {22, "HaveShadow"},
         {23, "HaveScreamer"},
         {24, "HaveRadar"},
         {25, "HaveBanner"},
         {26, "GetCurrSupplyCenterAssemblyPositionZ"},
         {27, "GetCurrSupplyCenterAssemblyPositionY"},
         {28, "GetCurrSupplyCenterAssemblyPositionX"},
         {29, "GetFoundSupplyCenterPlaceZ"},
         {30, "GetFoundSupplyCenterPlaceY"},
         {31, "GetFoundSupplyCenterPlaceX"},
         {32, "FindSupplyCenterPlace"},
         {33, "IsAllowingWithdraw"},
         {34, "AllowScriptWithdraw"},
         {35, "GetFoundArtefactZ"},
         {36, "GetFoundArtefactY"},
         {37, "GetFoundArtefactX"},
         {38, "FindArtefact"},
         {39, "FindArtefact"},
         {40, "FindClosestEnemyUnitOrBuilding"},
         {41, "FindClosestEnemyEx"},
         {42, "FindClosestEnemy"},
         {43, "EndEnumTargetsArray"},
         {44, "GetNextTarget"},
         {45, "StartEnumTargetsArray"},
         {46, "GetTargetsCount"},
         {47, "SortFoundTargetsArray"},
         {48, "BuildTargetsArray"},
         {49, "BuildTargetsArray"},
         {50, "FindTarget"},
         {51, "GetAngleToPoint"},
         {52, "GetAngleToTarget"},
         {53, "SetTargetObject"},
         {54, "ClearAttacker"},
         {55, "GetAttacker"},
         {56, "SendSupplyRequest"},
         {57, "CanBeTransported"},
         {58, "IsOnGround"},
         {59, "IsFreePoint"},
         {60, "SetLightsMode"},
         {61, "GetMoveLocationAngle"},
         {62, "GetMoveLocationZ"},
         {63, "GetMoveLocationY"},
         {64, "GetMoveLocationX"},
         {65, "GetLocationZ"},
         {66, "GetLocationY"},
         {67, "GetLocationX"},
         {68, "GetMaxHP"},
         {69, "GetHP"},
         {70, "IsDisabled"},
         {71, "IsLive"},
         {72, "IsGettingSupply"},
         {73, "IsMoving"},
         {74, "CallGetFlyingSupply"},
         {75, "CallTurnToAngle"},
         {76, "CallLand"},
         {77, "CallStopMoving"},
         {78, "CallMoveInsideObject"},
         {79, "CallMoveCountFields"},
         {80, "CallMoveOneField"},
         {81, "CallMoveLowToPointForce"},
         {82, "CallMoveLowToPoint"},
         {83, "CallMoveAndLandToPointForce"},
         {84, "CallMoveAndLandToPoint"},
         {85, "CallMoveToPointForce"},
         {86, "CallMoveToPoint"},
         {87, "GetUnitName"},
         {88, "SetUnitName"},
         {89, "GetBuildingType"},
         {90, "IsPlayer"},
         {91, "IsTransported"},
         {92, "GetAlphaAngle"},
         {93, "DistanceTo"},
         {94, "GetWorldBottom"},
         {95, "GetWorldRight"},
         {96, "GetWorldTop"},
         {97, "GetWorldLeft"},
         {98, "IsVisible"},
         {99, "IsAlliance"},
         {100, "IsNeutral"},
         {101, "IsEnemy"},
         {102, "IsContainerInPoint"},
         {103, "GetResourcesCount"},
         {104, "IsResourceInPoint"},
         {105, "IsBlackFog"},
         {106, "GetPlayerSideColor"},
         {107, "GetSideColor"},
         {108, "HaveEmptyCall"},
         {109, "NextCommand"},
         {110, "IsFroozen"},
         {111, "CallFreeze"},
         {112, "IsPassive"},
         {113, "IsTransporter"},
         {114, "IsSupplier"},
         {115, "IsSapper"},
         {116, "IsRepairer"},
         {117, "IsHarvester"},
         {118, "IsCarrier"},
         {119, "IsBuilder"},
         {120, "IsHelicopter"},
         {121, "IsLandUnit"},
         {122, "IsLandTarget"},
         {123, "IsBuilding"},
         {124, "GetIFFNumber"},
         {125, "GetIFF"},
         {126, "$Serialize"},
         {127, "$AddRef"},
         {128, "$Release"},
         {129, "$Serialize"},
         {130, "$AddRef"},
         {131, "$Release"},
         {132, "GetAmmoCount"},
         {133, "HaveCannonsMissingAmmo"},
         {134, "CanCannonTurnFullAngle"},
         {135, "GetCannonAngleToPoint"},
         {136, "GetCannonAngleToTarget"},
         {137, "CanCannonFireToGround"},
         {138, "CanCannonFireToAircraft"},
         {139, "CannonRequiresSupply"},
         {140, "StopCannonFire"},
         {141, "SetCannonFireMode"},
         {142, "IsPointInCannonRange"},
         {143, "IsTargetInCannonRange"},
         {144, "CannonFireGround"},
         {145, "CannonFireToTarget"},
         {146, "GetCannonSightRange"},
         {147, "GetCannonShootRange"},
         {148, "GetCannonType"},
         {149, "GetCannonsCount"},
         {150, "$Serialize"},
         {151, "$AddRef"},
         {152, "$Release"},
         {153, "$Serialize"},
         {154, "$AddRef"},
         {155, "$Release"},
         {156, "IsCurrentMineLineAndPoints"},
         {157, "IsCurrentMineAreaFar"},
         {158, "IsCurrentMineAreaMedium"},
         {159, "IsCurrentMineAreaClose"},
         {160, "IsCurrentMineArea"},
         {161, "NextMinePoint"},
         {162, "GetCurrMinePointZ"},
         {163, "GetCurrMinePointY"},
         {164, "GetCurrMinePointX"},
         {165, "HaveMinePoints"},
         {166, "ResetMinePoints"},
         {167, "AddMinePoint"},
         {168, "AddMineLine"},
         {169, "AddMineAreaFar"},
         {170, "AddMineAreaMedium"},
         {171, "AddMineAreaClose"},
         {172, "IsGoodPointForMine"},
         {173, "GetMinesCount"},
         {174, "HaveMines"},
         {175, "IsPuttingMine"},
         {176, "CallPutMine"},
         {177, "$Serialize"},
         {178, "$AddRef"},
         {179, "$Release"},
         {180, "FindHarvesterTransportBaseBuilding"},
         {181, "FindHarvesterRefineryBuilding"},
         {182, "GetFoundResourceZ"},
         {183, "GetFoundResourceY"},
         {184, "GetFoundResourceX"},
         {185, "FindResource"},
         {186, "HaveSomeResources"},
         {187, "HaveFullResources"},
         {188, "GetHarvesterBuildingPutLocationZ"},
         {189, "GetHarvesterBuildingPutLocationY"},
         {190, "GetHarvesterBuildingPutLocationX"},
         {191, "InvalidateCurrentHarvestPoint"},
         {192, "SetCurrentHarvestPoint"},
         {193, "GetHarvesterBuilding"},
         {194, "SetHarvesterBuilding"},
         {195, "IsPuttingResource"},
         {196, "IsHarvesting"},
         {197, "CallPutResource"},
         {198, "CallHarvest"},
         {199, "$Serialize"},
         {200, "$AddRef"},
         {201, "$Release"},
         {202, "FindSingleContainer"},
         {203, "FindContainerTransportBaseBuilding"},
         {204, "FindContainerRefineryBuilding"},
         {205, "FindContainerMineBuilding"},
         {206, "GetContainerTakeLocationZ"},
         {207, "GetContainerTakeLocationY"},
         {208, "GetContainerTakeLocationX"},
         {209, "GetDestinationBuildingPutLocationZ"},
         {210, "GetDestinationBuildingPutLocationY"},
         {211, "GetDestinationBuildingPutLocationX"},
         {212, "GetDestinationBuilding"},
         {213, "SetDestinationBuilding"},
         {214, "GetSourceBuildingTakeLocationZ"},
         {215, "GetSourceBuildingTakeLocationY"},
         {216, "GetSourceBuildingTakeLocationX"},
         {217, "GetSourceBuilding"},
         {218, "SetSourceBuilding"},
         {219, "HaveContainer"},
         {220, "IsPuttingContainer"},
         {221, "IsGettingContainer"},
         {222, "CallGetSingleContainer"},
         {223, "CallPutContainer"},
         {224, "CallGetContainer"},
         {225, "$Serialize"},
         {226, "$AddRef"},
         {227, "$Release"},
         {228, "SetUpgradeShield"},
         {229, "SetUpgradeChasis"},
         {230, "SetUpgradeWeapons"},
         {231, "SetRepaintSideColor"},
         {232, "GetOperateOnTargetLocationZ"},
         {233, "GetOperateOnTargetLocationY"},
         {234, "GetOperateOnTargetLocationX"},
         {235, "IsGoodPointForOperateOnTarget"},
         {236, "IsInGoodPointForOperateOnTarget"},
         {237, "CanBeUpgraded"},
         {238, "CanBeRepainted"},
         {239, "CanBeConverted"},
         {240, "CanBeRepaired"},
         {241, "CanUpgrade"},
         {242, "CanRepaint"},
         {243, "CanConvertHealthyBuildings"},
         {244, "CanConvertHealthyTanks"},
         {245, "CanConvertBuildings"},
         {246, "CanConvertTanks"},
         {247, "CanRepairBuildings"},
         {248, "CanRepairTanks"},
         {249, "IsUpgrading"},
         {250, "IsRepainting"},
         {251, "IsConverting"},
         {252, "IsRepairing"},
         {253, "CallUpgrade"},
         {254, "CallRepaint"},
         {255, "CallConvert"},
         {256, "CallRepair"},
         {257, "$Serialize"},
         {258, "$AddRef"},
         {259, "$Release"},
         {260, "FindSupplyCenter"},
         {261, "CheckCurrentPutSupplyLocation"},
         {262, "IsInGoodCurrentPutSupplyLocation"},
         {263, "GetCurrentPutSupplyPositionZ"},
         {264, "GetCurrentPutSupplyPositionY"},
         {265, "GetCurrentPutSupplyPositionX"},
         {266, "NextObjectForSupply"},
         {267, "WasCurrentObjectSupplied"},
         {268, "CanCurrentObjectBeSupplied"},
         {269, "GetCurrentObjectForSupply"},
         {270, "GetSupplyCenterAssemblyPositionZ"},
         {271, "GetSupplyCenterAssemblyPositionY"},
         {272, "GetSupplyCenterAssemblyPositionX"},
         {273, "GetSupplyCenterLoadPositionZ"},
         {274, "GetSupplyCenterLoadPositionY"},
         {275, "GetSupplyCenterLoadPositionX"},
         {276, "GetSupplyCenterBuilding"},
         {277, "SetSupplyCenterBuilding"},
         {278, "HaveObjectsForSupply"},
         {279, "IsPuttingAmmo"},
         {280, "IsLoadingAmmo"},
         {281, "CallPutAmmo"},
         {282, "CallLoadAmmo"},
         {283, "$Serialize"},
         {284, "$AddRef"},
         {285, "$Release"},
         {286, "NextElementPoint"},
         {287, "HaveElementsForBuild"},
         {288, "GetCurrentElementZ"},
         {289, "GetCurrentElementY"},
         {290, "GetCurrentElementX"},
         {291, "RemoveAllElements"},
         {292, "IsGoodElementPointForBuild"},
         {293, "AddElementPoint"},
         {294, "AddElementsLine"},
         {295, "GetCurrentBuildLocationZ"},
         {296, "GetCurrentBuildLocationY"},
         {297, "GetCurrentBuildLocationX"},
         {298, "IsGoodPointForCurrentBuild"},
         {299, "IsInGoodPointForCurrentBuild"},
         {300, "GetCurrentBuildType"},
         {301, "SetBuildTypeBuildElements"},
         {302, "SetBuildTypeBuildBuilding"},
         {303, "IsBuildWorking"},
         {304, "CallBuildCurrentElement"},
         {305, "CallBuildBuilding"},
         {306, "$Serialize"},
         {307, "$AddRef"},
         {308, "$Release"},
         {309, "InvalidateAutoPutPoint"},
         {310, "SetAutoPutPoint"},
         {311, "InvalidateAutoGetPoint"},
         {312, "SetAutoGetPoint"},
         {313, "GetFoundFreePlaceToPutUnitZ"},
         {314, "GetFoundFreePlaceToPutUnitY"},
         {315, "GetFoundFreePlaceToPutUnitX"},
         {316, "FindFreePlaceToPutUnitFromHook"},
         {317, "IsUnitToGetInPoint"},
         {318, "CanPutUnitFromHookInPoint"},
         {319, "HaveUnitOnHook"},
         {320, "IsDroppingUnit"},
         {321, "IsPuttingUnit"},
         {322, "IsGettingUnit"},
         {323, "CallDropUnit"},
         {324, "CallPutUnit"},
         {325, "CallGetUnit"},
         {326, "$Serialize"},
         {327, "$AddRef"},
         {328, "$Release"},
         {329, "GetType"},
         {330, "SwapUnits"},
         {331, "Turn"},
         {332, "EnableFeatures"},
         {333, "InPlatoon"},
         {334, "SetLeader"},
         {335, "GetPositionY"},
         {336, "GetPositionX"},
         {337, "SetPosition"},
         {338, "GetUnit"},
         {339, "GetUnitsCount"},
         {340, "GetCannonAngleToPoint"},
         {341, "GetCannonAngleToTarget"},
         {342, "ClearAttacker"},
         {343, "GetAttacker"},
         {344, "IsFrozen"},
         {345, "GetLocationZ"},
         {346, "GetLocationY"},
         {347, "GetLocationX"},
         {348, "CallTurnToAngle"},
         {349, "CallStopMoving"},
         {350, "IsMoving"},
         {351, "CallMoveToPoint"},
         {352, "RemoveUnitFromPlatoon"},
         {353, "AddUnitToPlatoon"},
         {354, "CanCannonFireToGround"},
         {355, "CanCannonFireToAircraft"},
         {356, "CannonRequiresSupply"},
         {357, "SetLightsMode"},
         {358, "SendSupplyRequest"},
         {359, "StopCannonFire"},
         {360, "SetCannonFireMode"},
         {361, "IsPointInCannonRange"},
         {362, "IsTargetInCannonRange"},
         {363, "CannonFireGround"},
         {364, "CannonFireToTarget"},
         {365, "GetCannonSightRange"},
         {366, "GetCannonShootRange"},
         {367, "GetCannonType"},
         {368, "GetCannonsCount"},
         {369, "Dispose"},
         {370, "KeepFormation"},
         {371, "FindClosestEnemyEx"},
         {372, "FindClosestEnemy"},
         {373, "EndEnumTargetsArray"},
         {374, "GetNextTarget"},
         {375, "StartEnumTargetsArray"},
         {376, "GetTargetsCount"},
         {377, "SortFoundTargetsArray"},
         {378, "BuildTargetsArray"},
         {379, "FindTarget"},
         {380, "HaveShadow"},
         {381, "HaveScreamer"},
         {382, "HaveRadar"},
         {383, "HaveBanner"},
         {384, "DistanceTo"},
         {385, "GetWorldBottom"},
         {386, "GetWorldRight"},
         {387, "GetWorldTop"},
         {388, "GetWorldLeft"},
         {389, "IsVisible"},
         {390, "IsAlliance"},
         {391, "IsNeutral"},
         {392, "IsEnemy"},
         {393, "GetPlayerSideColor"},
         {394, "GetSideColor"},
         {395, "NextCommand"},
         {396, "SetCannon"},
         {397, "SetAllCannons"},
         {398, "$Serialize"},
         {399, "EnableGameFeature"},
         {400, "PlayWave"},
         {401, "PlayWave"},
         {402, "PlayTrack"},
         {403, "SendCustomEvent"},
         {404, "GetDifficultyLevel"},
         {405, "SetTime"},
         {406, "EndGame"},
         {407, "GetAvailableWorlds"},
         {408, "SetAvailableWorlds"},
         {409, "MessageBox"},
         {410, "ShowVideo"},
         {411, "EnableInterface"},
         {412, "EnableCameraMovement"},
         {413, "LookAt"},
         {414, "LookAt"},
         {415, "LookAt"},
         {416, "LookAt"},
         {417, "RestoreCameraPosition2"},
         {418, "SaveCameraPosition2"},
         {419, "RestoreCameraPosition"},
         {420, "SaveCameraPosition"},
         {421, "GetMissionState"},
         {422, "SetMissionState"},
         {423, "SetSeason"},
         {424, "GetSeason"},
         {425, "GetMoneySentToOrbit"},
         {426, "SetPlayerSideColor"},
         {427, "GetPlayerSideColor"},
         {428, "CreateGamePlayer"},
         {429, "EnableChooseMissionButton"},
         {430, "SetTimer"},
         {431, "SetActivePlayerAndWorld"},
         {432, "ForceKeepBitmapAfterStatistic"},
         {433, "ForceCloseLoadProgress"},
         {434, "ForceKeepLoadProgress"},
         {435, "LoadBase"},
         {436, "LoadMission"},
         {437, "GetCurrentMission"},
         {438, "GetNextMission"},
         {439, "AreMissionsActiveEq"},
         {440, "AreMissionsEnabledEq"},
         {441, "AreMissionsActive"},
         {442, "AreMissionsEnabled"},
         {443, "IsMissionActive"},
         {444, "IsMissionEnabled"},
         {445, "ActivateMissions"},
         {446, "ActivateMissionsEq"},
         {447, "EnableMissions"},
         {448, "EnableMissionsEq"},
         {449, "ActivateMission"},
         {450, "EnableMission"},
         {451, "RegisterMission"},
         {452, "RegisterMission"},
         {453, "RegisterMission"},
         {454, "RegisterMission"},
         {455, "RegisterMission"},
         {456, "GetCampaignTime"},
         {457, "$Serialize"},
         {458, "GetMaxDistance"},
         {459, "SetMaxDistance"},
         {460, "IsAllowGiveUnits"},
         {461, "SetAllowGiveUnits"},
         {462, "CreateUnitEx"},
         {463, "CreateUnitEx"},
         {464, "GetMainEnemy"},
         {465, "GetMoneyFromFinishedMissions"},
         {466, "IsNeutral"},
         {467, "IsAlly"},
         {468, "IsEnemy"},
         {469, "IsAlive"},
         {470, "IsAllowGiveMoney"},
         {471, "SetAllowGiveMoney"},
         {472, "GetMaxAttackFrequency"},
         {473, "SetMaxAttackFrequency"},
         {474, "ClearPreferenceList"},
         {475, "AddToPreferenceList"},
         {476, "ClearMainTargetList"},
         {477, "AddToMainTargetList"},
         {478, "CopyResearches"},
         {479, "EnableStatistics"},
         {480, "LoadScript"},
         {481, "SetNumberOfDefensiveHelicopterPlatoons"},
         {482, "SetNumberOfDefensiveShipPlatoons"},
         {483, "SetNumberOfDefensiveTankPlatoons"},
         {484, "SetNumberOfOffensiveHelicopterPlatoons"},
         {485, "SetNumberOfOffensiveShipPlatoons"},
         {486, "SetNumberOfOffensiveTankPlatoons"},
         {487, "SetMaxShipPlatoonSize"},
         {488, "SetMaxHelicopterPlatoonSize"},
         {489, "SetMaxTankPlatoonSize"},
         {490, "ChooseEnemy"},
         {491, "RussianAttack"},
         {492, "Attack"},
         {493, "Attack"},
         {494, "RussianAttack"},
         {495, "CreateDefaultUnit"},
         {496, "GetRace"},
         {497, "CreateUnit"},
         {498, "AddUnitToSpecialTab"},
         {499, "GetDefaultUnitsRecyclePercent"},
         {500, "SetDefaultUnitsRecyclePercent"},
         {501, "GetBuildingTypeRecyclePercent"},
         {502, "SetBuildingTypeRecyclePercent"},
         {503, "IsCommandDisabled"},
         {504, "IsCommandEnabled"},
         {505, "EnableCommand"},
         {506, "EnableBuilding"},
         {507, "AddResearch"},
         {508, "EnableResearch"},
         {509, "SetSideColor"},
         {510, "GetSideColor"},
         {511, "GetIFFNumber"},
         {512, "GetIFF"},
         {513, "SetPointToQuarter"},
         {514, "SetPointToAvoid"},
         {515, "SetPointToGuard"},
         {516, "SetPointToAssemble"},
         {517, "GetMilitaryUnitsLimit"},
         {518, "SetMilitaryUnitsLimit"},
         {519, "EnableMilitaryUnitsLimit"},
         {520, "EnableSendingToBase"},
         {521, "GetMoneySentToOrbit"},
         {522, "GetMoneySentToBase"},
         {523, "GetMoneyCollectedByNow"},
         {524, "GetName"},
         {525, "SetName"},
         {526, "DelayedLookAt"},
         {527, "LookAt"},
         {528, "Victory"},
         {529, "Defeat"},
         {530, "IsPointLocated"},
         {531, "IsPointLocated"},
         {532, "GetStartingPointY"},
         {533, "GetStartingPointX"},
         {534, "EnableAIFeatures2"},
         {535, "EnableAIFeatures"},
         {536, "EnableAI"},
         {537, "GetNumberOfBuildings"},
         {538, "GetNumberOfBuildings"},
         {539, "GetNumberOfBuildings"},
         {540, "GetNumberOfUnits"},
         {541, "GetNumberOfUnits"},
         {542, "GetNumberOfUnits"},
         {543, "GiveTo"},
         {544, "GiveAllBuildingsTo"},
         {545, "GiveAllBuildingsTo"},
         {546, "GiveAllUnitsTo"},
         {547, "GiveAllUnitsTo"},
         {548, "GetScriptUnit"},
         {549, "SetScriptUnit"},
         {550, "SetScriptUnit"},
         {551, "GetScriptData"},
         {552, "SetScriptData"},
         {553, "SetAlly"},
         {554, "SetNeutral"},
         {555, "SetEnemy"},
         {556, "GetMoney"},
         {557, "SetMoney"},
         {558, "AddMoney"},
         {559, "$Serialize"},
         {560, "$AddRef"},
         {561, "$Release"},
         {562, "SetConsoleTextCol"},
         {563, "SetConsoleTextCol"},
         {564, "SetConsoleTextCol"},
         {565, "SetConsoleTextCol"},
         {566, "SetConsoleTextCol"},
         {567, "SetConsoleTextCol"},
         {568, "SetConsoleTextCol"},
         {569, "SetConsoleTextCol"},
         {570, "SetConsoleTextCol"},
         {571, "SetConsoleTextCol"},
         {572, "SetConsoleTextCol"},
         {573, "SetConsoleTextCol"},
         {574, "SetConsoleTextCol"},
         {575, "SetConsoleTextCol"},
         {576, "SetConsoleTextCol"},
         {577, "SetConsoleTextCol"},
         {578, "SetConsoleTextCol"},
         {579, "SetConsoleTextCol"},
         {580, "SetConsoleTextCol"},
         {581, "SetConsoleTextCol"},
         {582, "SetConsoleTextCol"},
         {583, "SetConsoleTextCol"},
         {584, "SetConsoleTextCol"},
         {585, "SetConsoleTextCol"},
         {586, "SetConsoleTextCol"},
         {587, "SetConsoleTextCol"},
         {588, "SetConsoleTextCol"},
         {589, "SetConsoleTextCol"},
         {590, "SetConsoleTextCol"},
         {591, "SetConsoleTextCol"},
         {592, "SetConsoleTextCol"},
         {593, "SetConsoleTextCol"},
         {594, "SetConsoleTextCol"},
         {595, "SetConsoleTextCol"},
         {596, "SetConsoleTextCol"},
         {597, "SetConsoleTextCol"},
         {598, "SetConsoleTextCol"},
         {599, "SetConsoleTextCol"},
         {600, "SetConsoleTextCol"},
         {601, "SetConsoleTextCol"},
         {602, "SetConsoleTextCol"},
         {603, "SetConsoleTextCol"},
         {604, "SetConsoleTextCol"},
         {605, "SetConsoleTextCol"},
         {606, "SetConsoleTextCol"},
         {607, "SetConsoleTextCol"},
         {608, "SetConsoleTextCol"},
         {609, "SetConsoleTextCol"},
         {610, "SetConsoleTextCol"},
         {611, "SetConsoleTextCol"},
         {612, "SetConsoleTextCol"},
         {613, "SetConsoleTextCol"},
         {614, "SetConsoleTextCol"},
         {615, "SetConsoleTextCol"},
         {616, "SetConsoleTextCol"},
         {617, "SetConsoleTextCol"},
         {618, "SetConsoleTextCol"},
         {619, "SetConsoleTextCol"},
         {620, "SetConsoleTextCol"},
         {621, "SetConsoleTextCol"},
         {622, "SetConsoleTextCol"},
         {623, "SetConsoleTextCol"},
         {624, "SetConsoleTextCol"},
         {625, "SetConsoleTextCol"},
         {626, "SetConsoleTextCol"},
         {627, "SetConsoleTextCol"},
         {628, "SetConsoleTextCol"},
         {629, "SetConsoleTextCol"},
         {630, "SetConsoleTextCol"},
         {631, "SetConsoleTextCol"},
         {632, "SetConsoleTextCol"},
         {633, "SetConsoleTextCol"},
         {634, "SetConsoleTextCol"},
         {635, "SetConsoleTextCol"},
         {636, "SetConsoleTextCol"},
         {637, "SetConsoleTextCol"},
         {638, "SetConsoleTextCol"},
         {639, "SetConsoleTextCol"},
         {640, "SetConsoleTextCol"},
         {641, "SetConsoleTextCol"},
         {642, "SetConsoleTextCol"},
         {643, "SetConsoleTextCol"},
         {644, "SetConsoleTextCol"},
         {645, "SetConsoleTextCol"},
         {646, "SetConsoleTextCol"},
         {647, "SetConsoleTextCol"},
         {648, "SetConsoleTextCol"},
         {649, "SetConsoleTextCol"},
         {650, "SetConsoleTextCol"},
         {651, "SetConsoleTextCol"},
         {652, "SetConsoleTextCol"},
         {653, "SetConsoleTextCol"},
         {654, "SetConsoleTextCol"},
         {655, "SetConsoleTextCol"},
         {656, "SetConsoleTextCol"},
         {657, "SetConsoleTextCol"},
         {658, "SetConsoleTextCol"},
         {659, "SetConsoleTextCol"},
         {660, "SetConsoleTextCol"},
         {661, "SetConsoleTextCol"},
         {662, "SetConsoleTextCol"},
         {663, "SetConsoleTextCol"},
         {664, "SetConsoleTextCol"},
         {665, "SetConsoleTextCol"},
         {666, "SetConsoleTextCol"},
         {667, "SetConsoleTextCol"},
         {668, "SetConsoleTextCol"},
         {669, "SetConsoleTextCol"},
         {670, "SetConsoleTextCol"},
         {671, "SetConsoleTextCol"},
         {672, "SetConsoleTextCol"},
         {673, "SetConsoleTextCol"},
         {674, "SetConsoleTextCol"},
         {675, "SetConsoleTextCol"},
         {676, "SetConsoleTextCol"},
         {677, "SetConsoleTextCol"},
         {678, "SetConsoleTextCol"},
         {679, "SetConsoleTextCol"},
         {680, "SetConsoleTextCol"},
         {681, "SetConsoleTextCol"},
         {682, "SetConsoleTextCol"},
         {683, "SetConsoleTextCol"},
         {684, "SetConsoleTextCol"},
         {685, "SetConsoleTextCol"},
         {686, "SetConsoleTextCol"},
         {687, "SetConsoleTextCol"},
         {688, "SetConsoleText"},
         {689, "SetConsoleText"},
         {690, "SetConsoleText"},
         {691, "SetConsoleText"},
         {692, "SetConsoleText"},
         {693, "SetConsoleText"},
         {694, "SetConsoleText"},
         {695, "SetConsoleText"},
         {696, "SetConsoleText"},
         {697, "SetConsoleText"},
         {698, "SetConsoleText"},
         {699, "SetConsoleText"},
         {700, "SetConsoleText"},
         {701, "SetConsoleText"},
         {702, "SetConsoleText"},
         {703, "SetConsoleText"},
         {704, "SetConsoleText"},
         {705, "SetConsoleText"},
         {706, "SetConsoleText"},
         {707, "SetConsoleText"},
         {708, "SetConsoleText"},
         {709, "SetConsoleText"},
         {710, "SetConsoleText"},
         {711, "SetConsoleText"},
         {712, "SetConsoleText"},
         {713, "SetConsoleText"},
         {714, "SetConsoleText"},
         {715, "SetConsoleText"},
         {716, "SetConsoleText"},
         {717, "SetConsoleText"},
         {718, "SetConsoleText"},
         {719, "SetConsoleText"},
         {720, "SetConsoleText"},
         {721, "SetConsoleText"},
         {722, "SetConsoleText"},
         {723, "SetConsoleText"},
         {724, "SetConsoleText"},
         {725, "SetConsoleText"},
         {726, "SetConsoleText"},
         {727, "SetConsoleText"},
         {728, "SetConsoleText"},
         {729, "SetConsoleText"},
         {730, "SetConsoleText"},
         {731, "SetConsoleText"},
         {732, "SetConsoleText"},
         {733, "SetConsoleText"},
         {734, "SetConsoleText"},
         {735, "SetConsoleText"},
         {736, "SetConsoleText"},
         {737, "SetConsoleText"},
         {738, "SetConsoleText"},
         {739, "SetConsoleText"},
         {740, "SetConsoleText"},
         {741, "SetConsoleText"},
         {742, "SetConsoleText"},
         {743, "SetConsoleText"},
         {744, "SetConsoleText"},
         {745, "SetConsoleText"},
         {746, "SetConsoleText"},
         {747, "SetConsoleText"},
         {748, "SetConsoleText"},
         {749, "SetConsoleText"},
         {750, "SetConsoleText"},
         {751, "SetConsoleText"},
         {752, "SetConsoleText"},
         {753, "SetConsoleText"},
         {754, "SetConsoleText"},
         {755, "SetConsoleText"},
         {756, "SetConsoleText"},
         {757, "SetConsoleText"},
         {758, "SetConsoleText"},
         {759, "SetConsoleText"},
         {760, "SetConsoleText"},
         {761, "SetConsoleText"},
         {762, "SetConsoleText"},
         {763, "SetConsoleText"},
         {764, "SetConsoleText"},
         {765, "SetConsoleText"},
         {766, "SetConsoleText"},
         {767, "SetConsoleText"},
         {768, "SetConsoleText"},
         {769, "SetConsoleText"},
         {770, "SetConsoleText"},
         {771, "SetConsoleText"},
         {772, "SetConsoleText"},
         {773, "SetConsoleText"},
         {774, "SetConsoleText"},
         {775, "SetConsoleText"},
         {776, "SetConsoleText"},
         {777, "SetConsoleText"},
         {778, "SetConsoleText"},
         {779, "SetConsoleText"},
         {780, "SetConsoleText"},
         {781, "SetConsoleText"},
         {782, "SetConsoleText"},
         {783, "SetConsoleText"},
         {784, "SetConsoleText"},
         {785, "SetConsoleText"},
         {786, "SetConsoleText"},
         {787, "SetConsoleText"},
         {788, "SetConsoleText"},
         {789, "SetConsoleText"},
         {790, "SetConsoleText"},
         {791, "SetConsoleText"},
         {792, "SetConsoleText"},
         {793, "SetConsoleText"},
         {794, "SetConsoleText"},
         {795, "SetConsoleText"},
         {796, "SetConsoleText"},
         {797, "SetConsoleText"},
         {798, "SetConsoleText"},
         {799, "SetConsoleText"},
         {800, "SetConsoleText"},
         {801, "SetConsoleText"},
         {802, "SetConsoleText"},
         {803, "SetConsoleText"},
         {804, "SetConsoleText"},
         {805, "SetConsoleText"},
         {806, "SetConsoleText"},
         {807, "SetConsoleText"},
         {808, "SetConsoleText"},
         {809, "SetConsoleText"},
         {810, "SetConsoleText"},
         {811, "SetConsoleText"},
         {812, "SetConsoleText"},
         {813, "SetConsoleText"},
         {814, "AddBriefing"},
         {815, "AddBriefing"},
         {816, "AddBriefing"},
         {817, "AddBriefing"},
         {818, "AddBriefing"},
         {819, "AddBriefing"},
         {820, "AddBriefing"},
         {821, "AddBriefing"},
         {822, "AddBriefing"},
         {823, "AddBriefing"},
         {824, "AddBriefing"},
         {825, "AddBriefing"},
         {826, "AddBriefing"},
         {827, "AddBriefing"},
         {828, "AddBriefing"},
         {829, "AddBriefing"},
         {830, "AddBriefing"},
         {831, "AddBriefing"},
         {832, "AddBriefing"},
         {833, "AddBriefing"},
         {834, "AddBriefing"},
         {835, "AddBriefing"},
         {836, "AddBriefing"},
         {837, "AddBriefing"},
         {838, "AddBriefing"},
         {839, "AddBriefing"},
         {840, "AddBriefing"},
         {841, "AddBriefing"},
         {842, "AddBriefing"},
         {843, "AddBriefing"},
         {844, "AddBriefing"},
         {845, "AddBriefing"},
         {846, "AddBriefing"},
         {847, "AddBriefing"},
         {848, "AddBriefing"},
         {849, "AddBriefing"},
         {850, "AddBriefing"},
         {851, "AddBriefing"},
         {852, "AddBriefing"},
         {853, "AddBriefing"},
         {854, "AddBriefing"},
         {855, "AddBriefing"},
         {856, "AddBriefing"},
         {857, "AddBriefing"},
         {858, "AddBriefing"},
         {859, "AddBriefing"},
         {860, "AddBriefing"},
         {861, "AddBriefing"},
         {862, "AddBriefing"},
         {863, "AddBriefing"},
         {864, "AddBriefing"},
         {865, "AddBriefing"},
         {866, "AddBriefing"},
         {867, "AddBriefing"},
         {868, "AddBriefing"},
         {869, "AddBriefing"},
         {870, "AddBriefing"},
         {871, "AddBriefing"},
         {872, "AddBriefing"},
         {873, "AddBriefing"},
         {874, "AddBriefing"},
         {875, "AddBriefing"},
         {876, "AddBriefing"},
         {877, "AddBriefing"},
         {878, "AddBriefing"},
         {879, "AddBriefing"},
         {880, "AddBriefing"},
         {881, "AddBriefing"},
         {882, "AddBriefing"},
         {883, "AddBriefing"},
         {884, "AddBriefing"},
         {885, "AddBriefing"},
         {886, "AddBriefing"},
         {887, "AddBriefing"},
         {888, "AddBriefing"},
         {889, "AddBriefing"},
         {890, "AddBriefing"},
         {891, "AddBriefing"},
         {892, "AddBriefing"},
         {893, "AddBriefing"},
         {894, "AddBriefing"},
         {895, "AddBriefing"},
         {896, "AddBriefing"},
         {897, "AddBriefing"},
         {898, "AddBriefing"},
         {899, "AddBriefing"},
         {900, "AddBriefing"},
         {901, "AddBriefing"},
         {902, "AddBriefing"},
         {903, "AddBriefing"},
         {904, "AddBriefing"},
         {905, "AddBriefing"},
         {906, "AddBriefing"},
         {907, "AddBriefing"},
         {908, "AddBriefing"},
         {909, "AddBriefing"},
         {910, "AddBriefing"},
         {911, "AddBriefing"},
         {912, "AddBriefing"},
         {913, "AddBriefing"},
         {914, "AddBriefing"},
         {915, "AddBriefing"},
         {916, "AddBriefing"},
         {917, "AddBriefing"},
         {918, "AddBriefing"},
         {919, "AddBriefing"},
         {920, "AddBriefing"},
         {921, "AddBriefing"},
         {922, "AddBriefing"},
         {923, "AddBriefing"},
         {924, "AddBriefing"},
         {925, "AddBriefing"},
         {926, "AddBriefing"},
         {927, "AddBriefing"},
         {928, "AddBriefing"},
         {929, "AddBriefing"},
         {930, "AddBriefing"},
         {931, "AddBriefing"},
         {932, "AddBriefing"},
         {933, "AddBriefing"},
         {934, "AddBriefing"},
         {935, "AddBriefing"},
         {936, "AddBriefing"},
         {937, "AddBriefing"},
         {938, "AddBriefing"},
         {939, "AddBriefing"},
         {940, "RegisterGoal"},
         {941, "RegisterGoal"},
         {942, "RegisterGoal"},
         {943, "RegisterGoal"},
         {944, "RegisterGoal"},
         {945, "RegisterGoal"},
         {946, "RegisterGoal"},
         {947, "RegisterGoal"},
         {948, "RegisterGoal"},
         {949, "RegisterGoal"},
         {950, "RegisterGoal"},
         {951, "RegisterGoal"},
         {952, "RegisterGoal"},
         {953, "RegisterGoal"},
         {954, "RegisterGoal"},
         {955, "RegisterGoal"},
         {956, "RegisterGoal"},
         {957, "RegisterGoal"},
         {958, "RegisterGoal"},
         {959, "RegisterGoal"},
         {960, "RegisterGoal"},
         {961, "RegisterGoal"},
         {962, "RegisterGoal"},
         {963, "RegisterGoal"},
         {964, "RegisterGoal"},
         {965, "RegisterGoal"},
         {966, "RegisterGoal"},
         {967, "RegisterGoal"},
         {968, "RegisterGoal"},
         {969, "RegisterGoal"},
         {970, "RegisterGoal"},
         {971, "RegisterGoal"},
         {972, "RegisterGoal"},
         {973, "RegisterGoal"},
         {974, "RegisterGoal"},
         {975, "RegisterGoal"},
         {976, "RegisterGoal"},
         {977, "RegisterGoal"},
         {978, "RegisterGoal"},
         {979, "RegisterGoal"},
         {980, "RegisterGoal"},
         {981, "RegisterGoal"},
         {982, "RegisterGoal"},
         {983, "RegisterGoal"},
         {984, "RegisterGoal"},
         {985, "RegisterGoal"},
         {986, "RegisterGoal"},
         {987, "RegisterGoal"},
         {988, "RegisterGoal"},
         {989, "RegisterGoal"},
         {990, "RegisterGoal"},
         {991, "RegisterGoal"},
         {992, "RegisterGoal"},
         {993, "RegisterGoal"},
         {994, "RegisterGoal"},
         {995, "RegisterGoal"},
         {996, "RegisterGoal"},
         {997, "RegisterGoal"},
         {998, "RegisterGoal"},
         {999, "RegisterGoal"},
         {1000, "RegisterGoal"},
         {1001, "RegisterGoal"},
         {1002, "RegisterGoal"},
         {1003, "RegisterGoal"},
         {1004, "RegisterGoal"},
         {1005, "RegisterGoal"},
         {1006, "RegisterGoal"},
         {1007, "RegisterGoal"},
         {1008, "RegisterGoal"},
         {1009, "RegisterGoal"},
         {1010, "RegisterGoal"},
         {1011, "RegisterGoal"},
         {1012, "RegisterGoal"},
         {1013, "RegisterGoal"},
         {1014, "RegisterGoal"},
         {1015, "RegisterGoal"},
         {1016, "RegisterGoal"},
         {1017, "RegisterGoal"},
         {1018, "RegisterGoal"},
         {1019, "RegisterGoal"},
         {1020, "RegisterGoal"},
         {1021, "RegisterGoal"},
         {1022, "RegisterGoal"},
         {1023, "RegisterGoal"},
         {1024, "RegisterGoal"},
         {1025, "RegisterGoal"},
         {1026, "RegisterGoal"},
         {1027, "RegisterGoal"},
         {1028, "RegisterGoal"},
         {1029, "RegisterGoal"},
         {1030, "RegisterGoal"},
         {1031, "RegisterGoal"},
         {1032, "RegisterGoal"},
         {1033, "RegisterGoal"},
         {1034, "RegisterGoal"},
         {1035, "RegisterGoal"},
         {1036, "RegisterGoal"},
         {1037, "RegisterGoal"},
         {1038, "RegisterGoal"},
         {1039, "RegisterGoal"},
         {1040, "RegisterGoal"},
         {1041, "RegisterGoal"},
         {1042, "RegisterGoal"},
         {1043, "RegisterGoal"},
         {1044, "RegisterGoal"},
         {1045, "RegisterGoal"},
         {1046, "RegisterGoal"},
         {1047, "RegisterGoal"},
         {1048, "RegisterGoal"},
         {1049, "RegisterGoal"},
         {1050, "RegisterGoal"},
         {1051, "RegisterGoal"},
         {1052, "RegisterGoal"},
         {1053, "RegisterGoal"},
         {1054, "RegisterGoal"},
         {1055, "RegisterGoal"},
         {1056, "RegisterGoal"},
         {1057, "RegisterGoal"},
         {1058, "RegisterGoal"},
         {1059, "RegisterGoal"},
         {1060, "RegisterGoal"},
         {1061, "RegisterGoal"},
         {1062, "RegisterGoal"},
         {1063, "RegisterGoal"},
         {1064, "RegisterGoal"},
         {1065, "RegisterGoal"},
         {1066, "GetTerrainType"},
         {1067, "EnableBuildingSounds"},
         {1068, "EnableUnitSounds"},
         {1069, "SetConsoleTextCol"},
         {1070, "SetConsoleText"},
         {1071, "AddBriefing"},
         {1072, "RegisterGoal"},
         {1073, "SetTimeDivider"},
         {1074, "SetPriceDivider"},
         {1075, "SelectUnit"},
         {1076, "CreateArtefact"},
         {1077, "CreateArtefact"},
         {1078, "ResourcesLeftInMoney"},
         {1079, "GetPointZ"},
         {1080, "GetPointY"},
         {1081, "GetPointX"},
         {1082, "PointExist"},
         {1083, "ResourcesPerContainer"},
         {1084, "CallCamera"},
         {1085, "IsGoalEnabled"},
         {1086, "EnableMissionGoalsButton"},
         {1087, "EnableEndMissionButton"},
         {1088, "EnableEndMissionButton"},
         {1089, "GetBottom"},
         {1090, "GetTop"},
         {1091, "GetRight"},
         {1092, "GetLeft"},
         {1093, "GetUnit"},
         {1094, "GetUnit"},
         {1095, "HideArea"},
         {1096, "ShowArea"},
         {1097, "ShowArea"},
         {1098, "DamageArea"},
         {1099, "KillArea"},
         {1100, "Meteor"},
         {1101, "Lighting"},
         {1102, "Wind"},
         {1103, "MeteorRain"},
         {1104, "Storm"},
         {1105, "Snow"},
         {1106, "Rain"},
         {1107, "GetGoalState"},
         {1108, "SetGoalState"},
         {1109, "EnableGoal"},
         {1110, "GetPlayer"},
         {1111, "GetMissionTime"},
         {1112, "EndMission"},
         {1113, "SetTimer"},
         {1114, "EnableNextMission"},
         {1115, "GetWorldNum"},
         {1116, "$Serialize"},
         {1117, "BuildingRemoveCloud"},
         {1118, "BuildingCreateWind"},
         {1119, "BuildingCreateMeteorRain"},
         {1120, "BuildingCreateRainStorm"},
         {1121, "BuildingCreateSnow"},
         {1122, "BuildingCreateRain"},
         {1123, "SoldBuilding"},
         {1124, "BuildingAutodestruction"},
         {1125, "BuildingSuperAttack"},
         {1126, "BuildingTurnOnOff"},
         {1127, "CommandUserArea9"},
         {1128, "CommandUserArea8"},
         {1129, "CommandUserArea7"},
         {1130, "CommandUserArea6"},
         {1131, "CommandUserArea5"},
         {1132, "CommandUserArea4"},
         {1133, "CommandUserArea3"},
         {1134, "CommandUserArea2"},
         {1135, "CommandUserArea1"},
         {1136, "CommandUserArea0"},
         {1137, "CommandUserDoubleLine9"},
         {1138, "CommandUserDoubleLine8"},
         {1139, "CommandUserDoubleLine7"},
         {1140, "CommandUserDoubleLine6"},
         {1141, "CommandUserDoubleLine5"},
         {1142, "CommandUserDoubleLine4"},
         {1143, "CommandUserDoubleLine3"},
         {1144, "CommandUserDoubleLine2"},
         {1145, "CommandUserDoubleLine1"},
         {1146, "CommandUserDoubleLine0"},
         {1147, "CommandUserLine9"},
         {1148, "CommandUserLine8"},
         {1149, "CommandUserLine7"},
         {1150, "CommandUserLine6"},
         {1151, "CommandUserLine5"},
         {1152, "CommandUserLine4"},
         {1153, "CommandUserLine3"},
         {1154, "CommandUserLine2"},
         {1155, "CommandUserLine1"},
         {1156, "CommandUserLine0"},
         {1157, "CommandUserPoint9"},
         {1158, "CommandUserPoint8"},
         {1159, "CommandUserPoint7"},
         {1160, "CommandUserPoint6"},
         {1161, "CommandUserPoint5"},
         {1162, "CommandUserPoint4"},
         {1163, "CommandUserPoint3"},
         {1164, "CommandUserPoint2"},
         {1165, "CommandUserPoint1"},
         {1166, "CommandUserPoint0"},
         {1167, "CommandUserObject9"},
         {1168, "CommandUserObject8"},
         {1169, "CommandUserObject7"},
         {1170, "CommandUserObject6"},
         {1171, "CommandUserObject5"},
         {1172, "CommandUserObject4"},
         {1173, "CommandUserObject3"},
         {1174, "CommandUserObject2"},
         {1175, "CommandUserObject1"},
         {1176, "CommandUserObject0"},
         {1177, "CommandUserNoParam9"},
         {1178, "CommandUserNoParam8"},
         {1179, "CommandUserNoParam7"},
         {1180, "CommandUserNoParam6"},
         {1181, "CommandUserNoParam5"},
         {1182, "CommandUserNoParam4"},
         {1183, "CommandUserNoParam3"},
         {1184, "CommandUserNoParam2"},
         {1185, "CommandUserNoParam1"},
         {1186, "CommandUserNoParam0"},
         {1187, "CommandTransporterSetAutoPutUnit"},
         {1188, "CommandTransporterSetAutoGetUnit"},
         {1189, "CommandTransporterDropUnitToPoint"},
         {1190, "CommandTransporterDropUnit"},
         {1191, "CommandTransporterPutUnitToPoint"},
         {1192, "CommandTransporterPutUnit"},
         {1193, "CommandTransporterGetUnit"},
         {1194, "CommandMoveToSupplyCenterForLoad"},
         {1195, "CommandSetTransporterSupplyCenter"},
         {1196, "CommandFlyForSupply"},
         {1197, "CommandSendSupplyRequest"},
         {1198, "CommandEnter"},
         {1199, "CommandSetContainerDestination"},
         {1200, "CommandGetSingleContainer"},
         {1201, "CommandSetContainerSource"},
         {1202, "CommandUpgrade"},
         {1203, "CommandRepaint"},
         {1204, "CommandConvert"},
         {1205, "CommandRepair"},
         {1206, "CommandSetHarvestPoint"},
         {1207, "CommandPatrol"},
         {1208, "CommandHoldPosition"},
         {1209, "CommandEscort"},
         {1210, "CommandAttackOnPoint"},
         {1211, "CommandAttack"},
         {1212, "CommandMove"},
         {1213, "CommandLand"},
         {1214, "CommandStop"},
         {1215, "LoadScript"},
         {1216, "GetObjectRecyclePercent"},
         {1217, "SetObjectRecyclePercent"},
         {1218, "ExecuteRecord"},
         {1219, "RepeatRecordExecution"},
         {1220, "EndQuickRecord"},
         {1221, "BeginQuickRecord"},
         {1222, "EndRecord"},
         {1223, "BeginRecord"},
         {1224, "Repaint"},
         {1225, "ChangePlayer"},
         {1226, "IsInWorld"},
         {1227, "RegenerateTemperature"},
         {1228, "GetMaxTemperature"},
         {1229, "GetTemperature"},
         {1230, "RegenerateElectronics"},
         {1231, "GetMaxElectronics"},
         {1232, "GetElectronics"},
         {1233, "RegenerateShield"},
         {1234, "GetMaxShield"},
         {1235, "GetShield"},
         {1236, "RegenerateAmmo"},
         {1237, "GetMaxAmmo"},
         {1238, "GetAmmo"},
         {1239, "RegenerateHP"},
         {1240, "GetMaxHP"},
         {1241, "GetHP"},
         {1242, "$Serialize"},
         {1243, "$AddRef"},
         {1244, "$Release"},
         {1245, "BuildingRemoveCloud"},
         {1246, "BuildingCreateWind"},
         {1247, "BuildingCreateMeteorRain"},
         {1248, "BuildingCreateRainStorm"},
         {1249, "BuildingCreateSnow"},
         {1250, "BuildingCreateRain"},
         {1251, "SoldBuilding"},
         {1252, "BuildingAutodestruction"},
         {1253, "BuildingSuperAttack"},
         {1254, "BuildingTurnOnOff"},
         {1255, "CommandUserArea9"},
         {1256, "CommandUserArea8"},
         {1257, "CommandUserArea7"},
         {1258, "CommandUserArea6"},
         {1259, "CommandUserArea5"},
         {1260, "CommandUserArea4"},
         {1261, "CommandUserArea3"},
         {1262, "CommandUserArea2"},
         {1263, "CommandUserArea1"},
         {1264, "CommandUserArea0"},
         {1265, "CommandUserDoubleLine9"},
         {1266, "CommandUserDoubleLine8"},
         {1267, "CommandUserDoubleLine7"},
         {1268, "CommandUserDoubleLine6"},
         {1269, "CommandUserDoubleLine5"},
         {1270, "CommandUserDoubleLine4"},
         {1271, "CommandUserDoubleLine3"},
         {1272, "CommandUserDoubleLine2"},
         {1273, "CommandUserDoubleLine1"},
         {1274, "CommandUserDoubleLine0"},
         {1275, "CommandUserLine9"},
         {1276, "CommandUserLine8"},
         {1277, "CommandUserLine7"},
         {1278, "CommandUserLine6"},
         {1279, "CommandUserLine5"},
         {1280, "CommandUserLine4"},
         {1281, "CommandUserLine3"},
         {1282, "CommandUserLine2"},
         {1283, "CommandUserLine1"},
         {1284, "CommandUserLine0"},
         {1285, "CommandUserPoint9"},
         {1286, "CommandUserPoint8"},
         {1287, "CommandUserPoint7"},
         {1288, "CommandUserPoint6"},
         {1289, "CommandUserPoint5"},
         {1290, "CommandUserPoint4"},
         {1291, "CommandUserPoint3"},
         {1292, "CommandUserPoint2"},
         {1293, "CommandUserPoint1"},
         {1294, "CommandUserPoint0"},
         {1295, "CommandUserObject9"},
         {1296, "CommandUserObject8"},
         {1297, "CommandUserObject7"},
         {1298, "CommandUserObject6"},
         {1299, "CommandUserObject5"},
         {1300, "CommandUserObject4"},
         {1301, "CommandUserObject3"},
         {1302, "CommandUserObject2"},
         {1303, "CommandUserObject1"},
         {1304, "CommandUserObject0"},
         {1305, "CommandUserNoParam9"},
         {1306, "CommandUserNoParam8"},
         {1307, "CommandUserNoParam7"},
         {1308, "CommandUserNoParam6"},
         {1309, "CommandUserNoParam5"},
         {1310, "CommandUserNoParam4"},
         {1311, "CommandUserNoParam3"},
         {1312, "CommandUserNoParam2"},
         {1313, "CommandUserNoParam1"},
         {1314, "CommandUserNoParam0"},
         {1315, "CommandTransporterSetAutoPutUnit"},
         {1316, "CommandTransporterSetAutoGetUnit"},
         {1317, "CommandTransporterDropUnitToPoint"},
         {1318, "CommandTransporterDropUnit"},
         {1319, "CommandTransporterPutUnitToPoint"},
         {1320, "CommandTransporterPutUnit"},
         {1321, "CommandTransporterGetUnit"},
         {1322, "CommandMoveToSupplyCenterForLoad"},
         {1323, "CommandSetTransporterSupplyCenter"},
         {1324, "CommandFlyForSupply"},
         {1325, "CommandSendSupplyRequest"},
         {1326, "CommandEnter"},
         {1327, "CommandSetContainerDestination"},
         {1328, "CommandGetSingleContainer"},
         {1329, "CommandSetContainerSource"},
         {1330, "CommandUpgrade"},
         {1331, "CommandRepaint"},
         {1332, "CommandConvert"},
         {1333, "CommandRepair"},
         {1334, "CommandSetHarvestPoint"},
         {1335, "CommandPatrol"},
         {1336, "CommandHoldPosition"},
         {1337, "CommandEscort"},
         {1338, "CommandAttackOnPoint"},
         {1339, "CommandAttack"},
         {1340, "CommandMove"},
         {1341, "CommandLand"},
         {1342, "CommandStop"},
         {1343, "$Serialize"},
         {1344, "$AddRef"},
         {1345, "$Release"},
      };
   }
}
