name: .NET CI/CD

defaults:
  run:
    working-directory: src

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack EarthFileApi\\EarthFileApi.csproj -c Release
    - name: Publish to GitHub packages 
      run: dotnet nuget push /home/runner/work/EarthFileApi/EarthFileApi/src/EarthFileApi/bin/Release/*.nupkg -k ${GITHUB_TOKEN} -s https://api.nuget.org/v3/index.json --skip-duplicate
      env:
        GITHUB_TOKEN: ${{ secrets.NUGET_KEY }}

